In [3]:
import numpy as np

# 1. Create 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)


[1 2 3 4 5]


In [4]:
# 2. Create 2D array
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]


In [5]:
# 3. Matrix Addition
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A + B)


[[ 6  8]
 [10 12]]


In [6]:

# 4. Matrix Multiplication
print(np.dot(A, B))



[[19 22]
 [43 50]]


In [7]:
# 5. Mean & Std
print("Mean:", np.mean(arr1))
print("Std:", np.std(arr1))

Mean: 3.0
Std: 1.4142135623730951


Day 2

In [9]:
# 1. Random matrix
rand_mat = np.random.rand(3,3)
print(rand_mat)

[[0.47217199 0.23780438 0.23933277]
 [0.40213185 0.23160209 0.31608652]
 [0.45697735 0.40361394 0.62628505]]


In [10]:
# 2. Column Sum
print(np.sum(rand_mat, axis=0))



[1.3312812  0.87302041 1.18170434]


In [11]:
# 3. Row Mean
print(np.mean(rand_mat, axis=1))

[0.31643638 0.31660682 0.49562545]


In [12]:
# 4. Standard deviation
print(np.std(rand_mat))


0.12565839280661864


In [13]:
# 5. Transpose
print(rand_mat.T)

[[0.47217199 0.40213185 0.45697735]
 [0.23780438 0.23160209 0.40361394]
 [0.23933277 0.31608652 0.62628505]]
